import {
  Kicker, PageTitle, Standfirst, Byline, Section, Prose, Callout,
  StatGrid, DataTable, Footnote,
} from '../components/Editorial';
import {
  REPORT, PROMOTION_COUNTS, PROMOTION_INPUTS, SUPERSESSIONS,
  runId, mergeCount, merges, collisionCandidates, rejections,
} from '../data/promotion';

/**
 * Provenance — the ingestion gate, shown rather than asserted.
 *
 * `research/raw/` is a quarantine zone written by research agents. This page is
 * the record of what the promotion pipeline did to it on the run whose id is
 * printed at the top: what it merged and on what key, what it refused to merge,
 * and what it refused to promote at all.
 *
 * It makes no claim about any named person or company. The names below appear
 * only as strings that an entity resolver had to reason about.
 */

/** Long tables are truncated on the page; the report JSON carries every row. */
const SHOW_COLLISIONS = 60;
const SHOW_REJECTIONS = 40;

const DETECTOR_LABEL: Record<string, string> = {
  'shared-surname': 'shared surname',
  'shared-brand-token': 'shared brand token',
  'fuzzy-name': 'fuzzy name match',
  'exact-name-no-corroboration': 'exact name, no corroboration',
};

const RULE_LABEL: Record<string, string> = {
  'extract/parse': 'file did not parse',
  'extract/asOf': 'file carried no asOf',
  'extract/sources': 'file carried no sources',
  'ground/provenance': 'would draw an edge with no source',
  'ground/undated-figure': 'figure stated without a date',
  'ground/identity': 'no strong identifier — takes no edges',
  'resolve/separation-guard': 'merge would fuse two structurally separate groups',
};

const fmt = (n: number) => n.toLocaleString('en-IN');

export default function Provenance() {
  const c = PROMOTION_COUNTS;
  const allMerges = merges();
  const collisions = collisionCandidates();
  const fatal = rejections('fatal');
  const quarantined = rejections('quarantine');
  const shownCollisions = collisions.slice(0, SHOW_COLLISIONS);
  const shownRejections = [...fatal, ...quarantined].slice(0, SHOW_REJECTIONS);

  return (
    <article className="pb-20">
      <header className="pt-2 pb-6 border-b-2 border-border-light">
        <Kicker>Provenance · the ingestion gate, and what it refused</Kicker>
        <PageTitle>What was promoted, and what was not</PageTitle>
        <Standfirst>
          Research agents write to a quarantine directory. Nothing there is trusted. Between that
          directory and anything this platform publishes sits one script, which reads each raw file,
          resolves entities on strong keys only, tests every record against the provenance and date
          rules, and writes the report below. Merges are listed with the key that justified them. The
          pairs a careless matcher would have fused are listed too — none of them were.
        </Standfirst>
        <Byline>
          Run {runId()} · pipeline {REPORT.pipelineVersion} · {c.files} raw files · generated by{' '}
          {REPORT.generator}
        </Byline>
      </header>

      <Callout label="Run id" tone="note">
        <p>
          <code className="text-accent text-[15px]">{runId()}</code> — derived from a digest of the
          pipeline rules and of the bytes of every input file. No clock is read, so the same inputs
          always produce the same id, on any machine. Change one character in one raw file and the id
          changes with it. Every claim promoted in this run cites this id alongside its source.
        </p>
      </Callout>

      <StatGrid
        items={[
          { value: fmt(c.records), label: 'records extracted from the quarantine zone' },
          { value: fmt(c.entities), label: 'canonical entities after resolution' },
          { value: fmt(c.merges), label: 'merges, each on a strong key with a recorded rationale' },
          {
            value: fmt(c.collisionCandidates),
            label: 'collision candidates recorded and NOT merged',
            tone: 'sage',
          },
          { value: fmt(c.rejections), label: 'records the gate refused to promote' },
          { value: fmt(c.fatal), label: 'fatal rejections — these fail the build', tone: c.fatal ? 'rose' : 'sage' },
          { value: fmt(c.quarantined), label: 'quarantined: identity too weak to take an edge', tone: 'muted' },
          { value: fmt(c.promoted), label: 'records cleared for promotion' },
        ]}
      />

      <Section title="The four stages" note="Extraction → resolution → grounding → assembly">
        <Prose>
          <ol className="space-y-3 list-none pl-0">
            {[
              ['Extraction', 'Each raw file must parse, carry an asOf and carry top-level sources. A file failing any of the three is refused whole rather than partially trusted — a file with no date stamp cannot have its figures grounded, and a file with no sources cannot have its claims traced. Each file is then turned into records by a named adapter; a file with no adapter contributes nothing and says so, so an unread file is never mistaken for a validated one.'],
              ['Resolution', 'Two records become one entity only on a strong key: ISIN, CIN, NSE ticker, BSE scrip code, state code, or an exact normalised legal name. For a person, an exact name is not enough on its own — a shared constituency, party, office or affiliation must corroborate it. Every merge is recorded with its key, its rationale and a confidence.'],
              ['Grounding', 'A record that would draw an edge must carry its own sources unless its tier is alleged or analytic. Every figure must carry a date, at record level or inherited from the file. An entity with no strong identifier is quarantined as unresolved and draws no edges.'],
              ['Assembly', 'The report is written to research/promotion-report.json with a run id derived from its inputs. Superseded facts are carried as a changelog rather than applied silently.'],
            ].map(([t, b], i) => (
              <li key={t} className="border-l-2 border-border-light pl-4">
                <strong className="text-text">
                  {i + 1}. {t}
                </strong>
                <span className="block text-[14.5px] mt-0.5">{b}</span>
              </li>
            ))}
          </ol>
        </Prose>
      </Section>

      <Section title="Inputs" note="Per-file record counts and content digests, as read on this run">
        <DataTable
          columns={['File', 'As of', 'File sources', 'Records', 'Digest']}
          rows={PROMOTION_INPUTS.map((f) => [
            <code key="f" className="text-[12.5px]">{f.file}</code>,
            f.asOf ?? '—',
            String(f.sources),
            <span key="r" className="font-mono">{fmt(f.records)}</span>,
            <code key="d" className="text-[11.5px] text-text-muted">{f.digest.slice(0, 12)}</code>,
          ])}
          caption={`${fmt(c.records)} records extracted; ${fmt(c.entities)} canonical entities after resolution`}
        />
      </Section>

      <Section
        title="Merges"
        note={`${mergeCount()} merges, each with the strong key that justified it and a confidence`}
      >
        <Prose>
          <p>
            Confidence is a property of the <em>key</em>, not of a name looking similar. An ISIN or a
            CIN is unique by construction and scores highest; an exact legal name, after stripping
            legal-form suffixes, is the weakest key admitted here and is scored accordingly. Nothing
            below was merged because two strings resembled one another.
          </p>
        </Prose>
        <DataTable
          columns={['Key', 'Value', 'Records merged', 'Rationale', 'Confidence']}
          rows={allMerges.map((m) => [
            <code key="k" className="text-[12px] uppercase text-accent">{m.key}</code>,
            <code key="v" className="text-[12px]">{m.value}</code>,
            <span key="m" className="text-[13px]">
              {m.members.map((r) => (
                <span key={r.file + r.path} className="block">
                  {r.label}
                  <span className="text-text-muted"> · {r.file}:{r.path}</span>
                </span>
              ))}
            </span>,
            m.rationale,
            <span key="c" className="font-mono">{m.confidence.toFixed(2)}</span>,
          ])}
        />
      </Section>

      <Section
        title="Collision candidates"
        note="Pairs a naive matcher would have fused — none were"
      >
        <Callout label="The rule this table exists to enforce" tone="warn">
          <p>
            Name similarity resolves nothing. Two records describing organisations that begin with the
            same brand token, or two people sharing a surname, are near-misses and are recorded as such;
            they are not evidence that the entities are the same, and this page makes no claim that any
            pair below is related in any way. The similarity score is published so the refusal can be
            judged, never so it can be acted on.
          </p>
          <p>
            {Object.entries(REPORT.collisionDetectors)
              .sort((a, b) => b[1] - a[1])
              .map(([d, n]) => `${DETECTOR_LABEL[d] ?? d}: ${n}`)
              .join(' · ')}
            . All {fmt(collisions.length)} were left as distinct entities.
          </p>
        </Callout>
        <DataTable
          columns={['Detector', 'Record A', 'Record B', 'Similarity', 'Why it was not merged', 'Action']}
          rows={shownCollisions.map((x, i) => [
            <span key={`d${i}`} className="font-mono text-[11px] uppercase tracking-wide text-text-muted">
              {DETECTOR_LABEL[x.detector] ?? x.detector}
            </span>,
            <span key={`a${i}`}>
              {x.a.label}
              <span className="block text-[11.5px] text-text-muted font-mono">{x.a.file}:{x.a.path}</span>
            </span>,
            <span key={`b${i}`}>
              {x.b.label}
              <span className="block text-[11.5px] text-text-muted font-mono">{x.b.file}:{x.b.path}</span>
            </span>,
            <span key={`s${i}`} className="font-mono">{x.similarity.toFixed(2)}</span>,
            <span key={`r${i}`} className="text-[13px]">{x.reason}</span>,
            <span key={`x${i}`} className="font-mono text-[11px] text-rose">NOT MERGED</span>,
          ])}
          caption={
            collisions.length > SHOW_COLLISIONS
              ? `Showing the ${SHOW_COLLISIONS} highest-similarity of ${fmt(collisions.length)} candidates; research/promotion-report.json carries all of them`
              : `All ${fmt(collisions.length)} candidates`
          }
        />
      </Section>

      <Section
        title="Rejections"
        note={`${fmt(c.rejections)} records refused promotion — ${fmt(c.fatal)} fatal, ${fmt(c.quarantined)} quarantined`}
      >
        <DataTable
          columns={['Rule', 'What it catches', 'Count', 'Effect']}
          rows={Object.entries(REPORT.rejectionRules)
            .sort((a, b) => b[1] - a[1])
            .map(([rule, n]) => [
              <code key="r" className="text-[12px]">{rule}</code>,
              RULE_LABEL[rule] ?? rule,
              <span key="n" className="font-mono">{fmt(n)}</span>,
              rule.startsWith('ground/identity') ? 'not promoted; build continues' : 'fails the build',
            ])}
        />
        <Prose>
          <p>
            A quarantined record is the gate working rather than failing. A foreign shareholder, an
            unlisted subsidiary or a director with no start date cannot be identified by an ISIN, a CIN,
            a ticker, a constituency or an office with dates — so it is held as unresolved, and an
            unresolved entity is not allowed to be the endpoint of any edge. That refusal is the reason
            the graph does not accumulate plausible-looking relationships between entities nobody has
            actually identified.
          </p>
        </Prose>
        <DataTable
          columns={['Level', 'Record', 'Where', 'Reason']}
          rows={shownRejections.map((r, i) => [
            <span
              key={`l${i}`}
              className={`font-mono text-[10.5px] uppercase tracking-[0.12em] ${r.level === 'fatal' ? 'text-rose' : 'text-text-muted'}`}
            >
              {r.level}
            </span>,
            r.label,
            <code key={`w${i}`} className="text-[11.5px] text-text-muted">{r.file}:{r.path}</code>,
            <span key={`n${i}`} className="text-[13px]">{r.reason}</span>,
          ])}
          caption={
            c.rejections > SHOW_REJECTIONS
              ? `Showing ${SHOW_REJECTIONS} of ${fmt(c.rejections)}; research/promotion-report.json carries all of them`
              : `All ${fmt(c.rejections)} rejections`
          }
        />
      </Section>

      {SUPERSESSIONS.length > 0 && (
        <Section title="Supersession log" note="Changes the raw files report about their own prior state">
          <DataTable
            columns={['Date', 'Change', 'Source']}
            rows={SUPERSESSIONS.map((s, i) => [
              <span key={`d${i}`} className="font-mono text-[12px]">{s.date ?? '—'}</span>,
              <span key={`c${i}`} className="text-[13.5px]">{s.what}</span>,
              s.src ? (
                <a
                  key={`s${i}`}
                  href={s.src[1]}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[12px] underline underline-offset-2 hover:text-accent"
                >
                  {s.src[0]}
                </a>
              ) : (
                '—'
              ),
            ])}
            caption="Superseded facts are retained and stay addressable. Nothing is deleted."
          />
        </Section>
      )}

      <Footnote>
        <p>
          <strong>The quarantine boundary.</strong> <code>research/raw/</code> holds the unedited output
          of research agents with web access. It is not a data source; it is a proposal queue. Nothing
          there is trusted, nothing there is rendered, and nothing there reaches{' '}
          <code>src/data/</code> or <code>src/graph/</code> without passing the gate described on this
          page. A hallucinating researcher cannot corrupt the graph without first satisfying a rule
          written down here.
        </p>
        <p>
          <strong>Source and run id.</strong> Every claim this platform publishes traces to two things:
          a source, which says where the claim came from, and a run id, which says under which rules and
          over which bytes it was admitted. This run is <code>{runId()}</code>. Re-running{' '}
          <code>npm run promote</code> over the same raw files reproduces it exactly; a change to any
          raw file, or to any rule in the pipeline, produces a different one.
        </p>
        <p>
          <strong>Standing.</strong> This page describes an entity-resolution and grounding procedure. It
          asserts nothing about any named person or company. Names appear here only as strings the
          resolver had to reason about, and the pairs listed as collision candidates are listed
          <em> because they were kept apart</em>.
        </p>
      </Footnote>
    </article>
  );
}
